version: "3"
services:
    app:
        restart: always
        build:
          context: .
          dockerfile: Dockerfile
        environment:
            - DATABASE_URI=${DATABASE_URI}
            - SECRET=${SECRET}
        image: transitdata:latest
        depends_on:
          - cratedb
        ports:
            - "5000:5000"
        stdin_open: true
        tty: true
    cratedb:
        image: crate:latest
        ports:
          - "4200:4200"
