version: "3"
services:
    app:
        restart: always
        build: ./app
        depends_on: 
          - cratedb
        links:
            - cratedb
        ports:
            - "5000:5000"
          
    cratedb:
        restart: always
        image: crate:latest
        ports:
          - "192.168.99.101:4200:4200"
        environment:
          - SQLALCHEMY_DATABASE_URI = $(SQLALCHEMY_DATABASE_URI)
          - SECRET_KEY = $(SECRET_KEY)
