version: "3"
services:
    app:
        # build: .
        build:
          context: .
          dockerfile: Dockerfile
        image: transitdata:latest
        depends_on:
          - cratedb
        # links:
        #     - cratedb
        ports:
            - "5000:5000"
        stdin_open: true
        tty: true
    cratedb:
        # restart: always
        image: crate:latest
        ports:
          - "4200:4200"
        environment:
          - DATABASE_URI=crate://crate@cratedb:4200
          - SECRET=1234
